### ISSUE TITLE
`getUniversities()` gets all universities from our database and not UniStats

### ISSUE THREAD

**Issue by DanielArthurUK** [UniNinja/graphql-api#28]
The `getUniversities()` function in `index.js` pulls a list of Universities from our JSON database and not the UniStats API. This results in a very limited list of universities being returned:

![image](https://user-images.githubusercontent.com/12424960/38732594-a4762a94-3f16-11e8-90dd-8631e203acc5.png)

**Comment by DanielArthurUK** [comment]
@harrygcollins did your PR solve this issue?

**Comment by harrygcollins** [comment]
Yes, all sorted!
