### ISSUE TITLE
Change endpoint from `/v0` to `/v1`

### ISSUE THREAD

**Issue by DanielArthurUK** [UniNinja/graphql-api#35]
To migrate the API from v0.1.0 to v1.0.0 we will need to change the endpoint to `/v1` instead of the current `/v0`

**Comment by DanielArthurUK** [comment]
I think that the best way to achieve this is to create a constant variable:
```javascript
const SERVER_ENDPOINT='/v1'
```
and then replace all instances of `/v0` with `SERVER_ENDPOINT`

**Comment by LoicVerrall** [comment]
Solved with #56, @DanielArthurUK?
