### ISSUE TITLE
API endpoint returning Null for all queries. 

### ISSUE THREAD

**Issue by harrygcollins** [UniNinja/graphql-api#50]
Suspected UniStats Auth issue.

**Comment by DanielArthurUK** [comment]
@harrygcollins I will SSH onto one of our servers in the cluster to check out what the problem is. Thanks for flagging this up! 🎏

**Comment by DanielArthurUK** [comment]
@harrygcollins here is what the server is saying:
![image](https://user-images.githubusercontent.com/12424960/39210349-5c267c1a-4800-11e8-8038-7877b912f396.png)
Any idea of what this means: `RES: Username and password needed` ?

**Comment by harrygcollins** [comment]
Good find, that is a UniStats Auth Issue

**Comment by DanielArthurUK** [comment]
@harrygcollins I think I have found the problem. The travis build isn't passing through the UniStats API key at the moment - I will fix now!
